namespace TestRailNavigator.Models;

/// <summary>
/// A single in-flight test case awaiting user confirmation before being written to TestRail.
/// </summary>
/// <remarks>
/// <see cref="CaseDraft"/> is the per-row payload used by the <c>CreatePlanFromStory</c> wizard.
/// It is bound from the quick-edit grid and the full-edit draft page, and is never persisted
/// on the server — state is round-tripped via form POSTs so the "no writes until Confirm" rule
/// is enforced by construction.
/// </remarks>
public class CaseDraft
{
    /// <summary>
    /// Gets or sets the case title (required). Truncated to 250 characters on commit to honor the TestRail limit.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the preconditions text for the case.
    /// </summary>
    public string? Preconditions { get; set; }

    /// <summary>
    /// Gets or sets the test steps text, typically one step per line.
    /// </summary>
    public string? Steps { get; set; }

    /// <summary>
    /// Gets or sets the expected result text.
    /// </summary>
    public string? Expected { get; set; }

    /// <summary>
    /// Gets or sets whether this draft should be created on commit. Unchecked rows are skipped.
    /// </summary>
    public bool Include { get; set; } = true;

    /// <summary>
    /// Gets or sets the optional case type identifier (e.g. Functional, Regression).
    /// Exposed in the full-edit draft page; not in the quick-edit grid.
    /// </summary>
    public int? TypeId { get; set; }

    /// <summary>
    /// Gets or sets the optional case priority identifier.
    /// </summary>
    public int? PriorityId { get; set; }

    /// <summary>
    /// Gets or sets the optional external references (e.g. <c>AB#1234</c>).
    /// </summary>
    public string? Refs { get; set; }

    /// <summary>
    /// Gets or sets the optional template identifier (e.g. Test Case (Text), Test Case (Steps)).
    /// </summary>
    public int? TemplateId { get; set; }

    /// <summary>
    /// Gets or sets the optional time estimate (e.g. <c>30s</c>, <c>1m 45s</c>).
    /// </summary>
    public string? Estimate { get; set; }

    /// <summary>
    /// Gets or sets the original Title generated by the parser. Used by "Revert to parsed".
    /// </summary>
    public string? OriginalTitle { get; set; }

    /// <summary>
    /// Gets or sets the original Steps generated by the parser. Used by "Revert to parsed".
    /// </summary>
    public string? OriginalSteps { get; set; }

    /// <summary>
    /// Gets or sets the original Expected generated by the parser. Used by "Revert to parsed".
    /// </summary>
    public string? OriginalExpected { get; set; }

    /// <summary>
    /// Gets or sets the original Preconditions generated by the parser. Used by "Revert to parsed".
    /// </summary>
    public string? OriginalPreconditions { get; set; }

    /// <summary>
    /// Gets or sets the identifier of an existing TestRail case whose title matches this draft's
    /// (normalized, case-insensitive). Set by the server-side duplicate-title check on Confirm.
    /// Null when no duplicate exists. Display only — not round-tripped from the client.
    /// </summary>
    public int? DuplicateOfCaseId { get; set; }

    /// <summary>
    /// Gets or sets an LLM-authored one-paragraph summary of what the test verifies. Used with
    /// the "Test Case (Steps)" template (TemplateId = 2). Null on pure-parser scaffolds.
    /// </summary>
    public string? Summary { get; set; }

    /// <summary>
    /// Gets or sets the LLM-authored step/expected pairs. When populated the draft is committed
    /// against the "Test Case (Steps)" template. Null falls back to the plain
    /// <see cref="Steps"/> / <see cref="Expected"/> textareas.
    /// </summary>
    public List<Models.TestCaseStep>? StepsSeparated { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this draft has already been enriched by the LLM.
    /// Used by the UI to show a badge and to avoid re-spending tokens on repeated clicks.
    /// </summary>
    public bool Enriched { get; set; }
}
