apiVersion: v1
kind: Secret
metadata:
  name: {{ include "testrail-navigator.fullname" . }}-settings
  labels:
    {{- include "testrail-navigator.labels" . | nindent 4 }}
type: Opaque
stringData:
  testrail-settings.json: |
    {
      "BaseUrl": {{ .Values.testrail.baseUrl | quote }},
      "Username": {{ .Values.testrail.username | quote }},
      "ApiKey": {{ .Values.testrail.apiKey | quote }},
      "AllowWrites": {{ .Values.testrail.allowWrites }},
      "SetupUsername": {{ .Values.testrail.setupUsername | quote }},
      "SetupPassword": {{ .Values.testrail.setupPassword | quote }}
    }
